### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Alexchepa25** [Alexchepa25/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by AlexChepa** [comment]
Email: ryucool@verygmail.com
Phone: +1433667999
Twitter: twitter.com/unrealRyu
Instagram: https://www.instagram.com/unrealRyu

**Comment by Alexchepa25** [comment]
Ok
