### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Alexchepa25** [Alexchepa25/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by AlexChepa** [comment]
I am a fairly successful person and an invincible fighter. I met many very strong opponents, in my opinion, stronger than me. Strength is cool! But in a duel tactics are needed and attention is very important. Winners never lose!

**Comment by Alexchepa25** [comment]
Thank you.
